### ISSUE TITLE
Example is still not running The error I get is the following

### ISSUE THREAD

**Issue by andyfensham** [NetCoreApps/BookingsCrud#2]
I saw you updated the readme, but it is still not working.  I have now cloned the repo and still get an error.
Below see the error message

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ServiceStack.ModularStartup.Configure(IApplicationBuilder app) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack\ModularStartup.cs:line 250
   at ServiceStack.ModularStartupActivator.Configure(IApplicationBuilder app) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack\ModularStartup.cs:line 357
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Acme.Program.Main(String[] args) in C:\Dev\throwaway\test\BookingsCrud\Acme\Program.cs:line 15

  This exception was originally thrown at this call stack:
    ServiceStack.ServiceStackHost.OnStartupException(System.Exception) in ServiceStackHost.cs
    ServiceStack.ServiceStackHost.RunPostInitPlugin(object) in ServiceStackHost.cs
    System.Collections.Generic.List<T>.ForEach(System.Action<T>)
    ServiceStack.ServiceStackHost.AfterPluginsLoaded(string) in ServiceStackHost.cs
    ServiceStack.ServiceStackHost.OnAfterInit() in ServiceStackHost.cs
    ServiceStack.ServiceStackHost.Init() in ServiceStackHost.cs
    ServiceStack.NetCoreAppHostExtensions.UseServiceStack(Microsoft.AspNetCore.Builder.IApplicationBuilder, ServiceStack.AppHostBase) in AppHostBase.NetCore.cs
    Acme.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder, Microsoft.AspNetCore.Hosting.IWebHostEnvironment) in Startup.cs

Inner Exception 1:
MissingMethodException: Method not found: 'Boolean ServiceStack.Host.ServiceController.HasService(System.Type)'.

**Comment by mythz** [comment]
This is still the same error. You absolutely need to clear your NuGet packages cache:

    $ nuget locals all -clear

If you don't have the nuget tool in your systems `PATH` you can use `dotnet` tool:

    $ dotnet nuget locals all -clear
    
Please close all your IDEs before running the above commands, then capture the output and post it here so I can confirm that it's been run successfully.

**Comment by andyfensham** [comment]
Hi, Please see attached screenshot showing it has been cleared.  I will try again and then see.

![Snag_1ee4b3e](https://user-images.githubusercontent.com/5065306/122423861-8a728a00-cf8e-11eb-96dc-a5ab361a80f7.png)

**Comment by andyfensham** [comment]
I rebuilt the projects and ran it again and it is working now.  Is it normal to regularly clear nuget locals, or was it just a glitch.

**Comment by mythz** [comment]
As this project uses [NuGet.Config](https://github.com/NetCoreApps/BookingsCrud/blob/main/NuGet.Config) to reference the pre-release packages (which can be updated multiple times a day) you can get into a situation where different packages are restored at different times where by the dirty packages become incompatible. When this happens it will result in the Missing Type/Method exceptions as seen in your StackTrace at which point you would need to clear your NuGet packages cache to be able to redownload the latest version of each package.

Alternatively you could delete the `NuGet.config` and do a full restore so the App only references the immutable package references published on NuGet on each official major release.
